/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-124496-gdc74fe70b2-20260516"
#endif /* AVUTIL_FFVERSION_H */
